apiVersion: v1
kind: ServiceAccount
metadata:
  name: blue-green
---
apiVersion: v1
kind: Service
metadata:
  name: blue-green-svc
spec:
  selector:
    app: blue-green
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
  labels:
    app: blue-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue-green
      color: blue
  template:
    metadata:
      labels:
        app: blue-green
        color: blue
    spec:
      serviceAccountName: blue-green
      containers:
      - name: echo-container
        image: hashicorp/http-echo:0.2.3
        ports:
        - containerPort: 8080
        args:
          - "-text=response from blue-app"
          - -listen=:8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deployment
  labels:
    app: green-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue-green
      color: green
  template:
    metadata:
      labels:
        app: blue-green
        color: green
    spec:
      serviceAccountName: blue-green
      containers:
      - name: echo-container
        image: hashicorp/http-echo:0.2.3
        ports:
        - containerPort: 8080
        args:
          - "-text=response from green-app"
          - -listen=:8080